language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
rvm:
- 2.1.5
before_script: # any command in this section with exit code 1 fails build
- bundle exec rake ci:clone
- bundle exec rake site:build env=prod # prod build
- bundle exec rake site:validate
script:
- bundle exec rake ci:deploy

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speed up installation of html-proofer
